### ISSUE TITLE
nginx package cannot be downloaded

### ISSUE THREAD

**Issue by maxadamo** [ConsortiumGARR/idem-tutorials#18]
hello, this URL is no longer working: 
http://www.marcocappellacci.info/repository/nginx_1.10.1-1~jessie_amd64.deb

p.s.: it would be interesting to have scripts to compile the packages for different OSs (namely create rpm and deb).

**Comment by peppelinux** [comment]
Here we have nginx optionally, compiled from source:
https://github.com/peppelinux/Ansible-Shibboleth-IDP-SP-Debian

using LXC or other kind of containers there woudn't be any problem in system space package management.
