### ISSUE TITLE
Apache di jetty non parte

### ISSUE THREAD

**Issue by teopost** [ConsortiumGARR/idem-tutorials#22]
Ho eseguito passo passo la guida:

HOWTO Install and Configure a Shibboleth IdP v3.4.x on CentOS 7 with Apache2 + Jetty9

Arrivato al punto 11 della sezione "Install Jetty 9 Web Server" denominato "Check if the Apache Welcome page is available:" non ho rilevato alcun servizio apache in esecuzione.

NOTA: Il link per il download di jetty andrebbe modificato in :
* https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-distribution/9.4.26.v20200117/jetty-distribution-9.4.26.v20200117.tar.gz

**Comment by malavolti** [comment]
Grazie Stefano!
Ho provveduto ad aggiornare il link per Jetty e a rimuovere il check dal posto sbagliato. Non è possibile raggiungere la pagina HTTPS se prima non è stato abilitato...

Un caro saluto,
Marco Malavolti
