### ISSUE TITLE
Error: Unable to find a match: java-11-amazon-corretto-devel

### ISSUE THREAD

**Issue by PengKuang** [ConsortiumGARR/idem-tutorials#39]
Hello,

I'm trying to install Shibboleth Idp4.X on CentOS 8.  I saw this error when came to the step below:

[root@XXShibboleth ~]# yum install -y java-11-amazon-corretto-devel
Last metadata expiration check: 0:12:44 ago on Wed 28 Oct 2020 03:24:44 PM CST.
No match for argument: java-11-amazon-corretto-devel

Could you please let me know how to fix this?

Thanks,
Peng

**Comment by malavolti** [comment]
Hi!
I'm sorry for this late answer... :(

We've followed the instructions provided by Amazon here: 

https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/generic-linux-install.html#rpm-linux-install-instruct

Could you try them too and tell us if they solve your problem, please?

Thank you so much!
