### ISSUE TITLE
How to install nginx Shibboleth SP in Cent OS 7

### ISSUE THREAD

**Issue by rrjanbiah** [ConsortiumGARR/idem-tutorials#51]
There are tutorials for Apache/CentOS: https://github.com/ConsortiumGARR/idem-tutorials/blob/master/idem-fedops/HOWTO-Shibboleth/Service%20Provider/CentOS/HOWTO%20Install%20and%20Configure%20a%20Shibboleth%20SP%20v3.x%20on%20CentOS%207%20(x86_64).md

and Nginx/Debian: https://github.com/ConsortiumGARR/idem-tutorials/blob/master/idem-community/HOWTO-Shibboleth/Service-Provider/Debian/HOW%20TO%20SETUP%20A%20SHIBBOLETH%20SP%20WITH%20NGINX.md

But, greatly missing Nginx/Cent OS that's a popular combination for many live servers.

Already someone noted it https://stackoverflow.com/questions/49498613/how-to-configure-shibboleth-sp-running-on-nginx-web-server-on-centos-7

(For the sake of record, I tried combination of such tutorials; but none of them builds `nginx-http-shibboleth.so`)

**Comment by malavolti** [comment]
Hi!

Have you already tried to send an email to the Author of the "HOW TO SETUP A SHIBBOLETH SP WITH NGINX" 
Marco Cappellacci - Università degli Studi di Urbino Carlo Bo (marco.cappellacci@uniurb.it)?

Kind Regards,
Marco

**Comment by rrjanbiah** [comment]
@malavolti I believe it is @cappe87 Yes, I haven't directly emailed him as I thought opening a ticket here will do that.
