### ISSUE TITLE
 GPG Keys issue

### ISSUE THREAD

**Issue by krishmoodbidri** [ConsortiumGARR/idem-tutorials#53]
Failing package is: shibboleth-3.3.0-1.x86_64
Issue: GPG key is broken

Key URL: https://download.opensuse.org/repositories/security:/shibboleth/CentOS_7/repodata/repomd.xml.key
error on line 1 at column 1: Document is empty

my workaround has been to disable the  GPG Keys check
```yum install shibboleth --nogpgcheck```

This works fine but would be considered a temporary fix.

**Comment by malavolti** [comment]
Dear @krishmoodbidri ,

forgive me if we didn't answer to your issue before.

CentOS 7 now is deprecated and will not receive support anymore:

https://endoflife.date/centos

so, we have moved its HOWTO under "Deprecated" materials and we will not provide support for it anymore.

Thank you so much! Your help had been appreciated!
