### ISSUE TITLE
Shibboleth SP v3 extracts duplicate attribute value

### ISSUE THREAD

**Issue by saaditani** [ConsortiumGARR/idem-tutorials#56]
Dears,

I dont know if anyone encountered this problem before as I am having difficulty solving it.
Debian with Spv3 on apache and tomecat backend is extracting two duplicate attribute values for SchacHoneOrganization and Eppn. Any idea why this is happening two duplicate values instead of one value? Sur name and displayName are working fine. 
Also note that IDP is sending one value for each as I have checked it using the aacli script.

Thank you

**Comment by malavolti** [comment]
Dear @saaditani,

did you follow one of our HOWTO to setup your Shibboleth SP v3?

**Comment by saaditani** [comment]
Hi Marco,

Yes but without the Attrchecker part.

**Comment by malavolti** [comment]
Dear @saaditani ,

The Service Provider Shibboleth uses the "attribute-map.xml" configuration file to map the attributes received by the Shibboleth Identity Provider with their OID name into attributes identified by an 'id'. 

Into the example below you can see that the 'eppn' attribute provided by the IdP with the OID "urn:oid:1.3.6.1.4.1.5923.1.1.1.6" will be identified with the id="eppn" SP attribute that can be called on a PHP application with **$_SERVER["eppn"]**:

```
    <Attribute name="urn:oid:1.3.6.1.4.1.5923.1.1.1.6" id="eppn">
        <AttributeDecoder xsi:type="ScopedAttributeDecoder"/>
    </Attribute>
```

Is the 'attribute-map.xml' file configured correctly for 'eppn' and 'schacHomeOrganization'?

I suggest you to work with the simple "/secure" app and only Apache until the attributes received by the IdP are recognized correctly by the "secure" app.

Follow the Tutorial entirely from scratch and when all works as indicated, add the Tomcat part.

Good Luck!
Marco
