### ISSUE TITLE
Wrong Apache Instructions in README

### ISSUE THREAD

**Issue by hxtree** [ConsortiumGARR/idem-tutorials#7]
The following line refers to a Debian/Ubuntu install of Apache (apache2). While the rest of the instructions are for Centos Apache (httpd):

"Modify the file /etc/apache2/sites-available/default-ssl.conf as follows:"

This line et. al. should be changed to "/etc/httpd/sites-available" with mkdir and adding "IncludeOptional sites-enabled/*.conf" to "/etc/httpd/conf/httpd.conf" as the provided instructions will not work.

**Comment by malavolti** [comment]
Thank you so much! I'll fix it today when I'll reach the office! 😊

**Comment by malavolti** [comment]
I think I have fixed all now.

Thank you for the help!!!
