### ISSUE TITLE
build broken when build in docker as of 10-06-2019

### ISSUE THREAD

**Issue by fighne** [ConsortiumGARR/idem-tutorials#8]
- need to add nano and wget to install

- after adding key for nginx sources  'apt-get update' required

- nginx 1.16.0 is current build

- need instructions for key genertion or link https://www.akadia.com/services/ssh_test_certificate.html

- Add metadataprovider should have a pointer to where to add xml it qould be assumed to be inside the 'session' tag but should be outside

- the header files aren't moved to the correct dicrectory

**Comment by daserzw** [comment]
hi, you sure you wanted to open the issue above in this repo (which BTW is just a fork to contribute upstream)
